name: slides
adopt-info: slides
summary: Slides in your terminal.
description: |
  Slides in your terminal.
  
  Usage:
    slides <file.md> [flags]

  Flags:
    -h, --help   help for slides
    
license: MIT

base: core24
grade: stable 
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
  
assumes:
  - command-chain
  
apps:
  slides:
    command: bin/slides
    command-chain: 
      - bin/homeishome-launch     
    plugs:
      - home
      - ssh-keys
      - ssh-public-keys
      - network
      - network-bind
      
parts:
  slides:
    source: https://github.com/maaslalani/slides
    source-type: git
    plugin: go
    build-snaps:
      - go
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch     
